swagger: '2.0'
info: 
  title: Task Manager API 
  version: 1.0.0
  description: Created By Jigar Khalas 
  contact:
    name: Jigar Khalas
    email: khalasjigar0861@gmail.com
paths:
  /user/login:
    post:
      description: Login API 
      summary: Returns a token
      tags:
        - User 
      parameters:
        - in: body
          name: user
          schema:
            type: object
            properties: 
              email:  
                type: string 
              password: 
                type: string
            required:
              - email
              - password
      responses:
        200:
          description: Success
          schema:
            type: object
            properties: 
              status:
                type: integer
              message:
                type: string
              data: 
                type: string
            required:
              - data
              - status 
              - message
        404:
          description: User Not Found 
          schema:
            $ref: "#/definitions/error"
        401: 
          description: UnAuthorized
          schema: 
            $ref: "#/definitions/error"
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/error"
  /user/delete/{id}:
    delete:
      summary: Deletes a user by userId 
      tags:
        - User
      parameters:
        - in: path
          name: id 
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            type: object
            properties: 
              status:
                type: string
              message:
                type: string
            required:
              - status
              - message
        404:
          description: User Not Found
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal Server Error 
          schema:
            $ref: "#/definitions/error"
definitions:
  error:   
    type: object
    properties: 
      status:
        type: string
      message:
        type: string
    required:
      - status
      - message